os: Visual Studio 2017

environment:
  matrix:
    - fips: TRUE
      arch: Win32
    - fips: FALSE
      arch: Win32
    - fips: FALSE
      arch: x64

install:
  - set CMAKE_URL="https://cmake.org/files/v3.14/cmake-3.14.4-win32-x86.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps\cmake > nul
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version
  - git submodule update --init --recursive 

  # install NASM
  - cd \
  - appveyor DownloadFile "https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-win64.zip" -FileName "c:\nasm.zip"
  - 7z x "nasm.zip" > nul
  - move nasm-* NASM
  - set PATH=%PATH%;c:\NASM;
  - nasm -v

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -DBUILD_OPENSSL=true -DOSSL_SUPPORT_UNAME=%OSSL_SUPPORT_UNAME% -DOSSL_SUPPORT_PASS=%OSSL_SUPPORT_PASS% -DFIPS=%fips% -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=true -G "Visual Studio 15 2017" -A %arch% ..
  - msbuild WickrCryptoC.sln /p:Configuration=Release
  - cd test\Release
  - crypto_test.exe --ci
